#!/bin/bash
let result=0
for file in /var/log/*; do
	if [[ "$file" =~ .+\.log ]]; then
		if [ -r "$file" ]; then
			let lines=$(wc -l "$file" | awk '{print $1}')
			let result=result+lines
		fi
	fi
done
echo "$result"

