#!/bin/bash
git=".gid"
file_name=(basename "$1")
if [[ "$2" == "create" ]]; then
	if [ ! -d "$git" ]; then
		mkdir "$git"
	fi
	if [ ! -f "$1" ]; then
		touch "$1"
	fi
	ln "$1" "$git/$file_name-link"
	cp "$1" "$git/"
	touch "$git/$file_name.log"
elif [[ "$2" == "check" ]]; then
	if [ -f "$git/$file_name" ]; then
		diff "$1" "$git/$file_name" >> "$"
	fi
fi
