#!/bin/bash
#top -u user -b -n 1 | sed -n '/PID/,$p' | grep 'user' | wc -l > out1
#top -u user -b -n 1 | sed -n '/PID/,$p' | grep 'user' | awk '{printf "%s:%s\n", $1, $12}' >> out1
ps aux | awk '$1 == "user"{print $0}' |  wc -l > out1
ps aux | awk '$1 == "user"{printf "%s:%s\n", $1, $11}' >> out1

