#!/bin/bash
echo $$ > .pid
mode="add"
result=1
usr1() {
	mode="add"
}
usr2() {
	mode="mult"
}
sigterm() {
	echo "Killed using sigterm"
	exit 0
}
trap 'usr1' USR1
trap 'usr2' USR2
trap 'sigterm' SIGTERM
while true; do
	case $mode in
		add)
			let result=$result+2
			;;
		mult)
			let result=$result\*2
			;;
	esac
	echo $result
	sleep 1
done
